<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\Announcements\Commands\DeleteAnnouncement\**" />
    <Compile Remove="Features\Announcements\Commands\UpdateAnnouncement\**" />
    <Compile Remove="Features\Announcements\Queries\**" />
    <Compile Remove="Features\Organizations\**" />
    <Compile Remove="Features\ProjectImages\**" />
    <Compile Remove="Features\Projects\**" />
    <EmbeddedResource Remove="Features\Announcements\Commands\DeleteAnnouncement\**" />
    <EmbeddedResource Remove="Features\Announcements\Commands\UpdateAnnouncement\**" />
    <EmbeddedResource Remove="Features\Announcements\Queries\**" />
    <EmbeddedResource Remove="Features\Organizations\**" />
    <EmbeddedResource Remove="Features\ProjectImages\**" />
    <EmbeddedResource Remove="Features\Projects\**" />
    <None Remove="Features\Announcements\Commands\DeleteAnnouncement\**" />
    <None Remove="Features\Announcements\Commands\UpdateAnnouncement\**" />
    <None Remove="Features\Announcements\Queries\**" />
    <None Remove="Features\Organizations\**" />
    <None Remove="Features\ProjectImages\**" />
    <None Remove="Features\Projects\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\AssignmentSubmission\Commands\DeleteAssignmentSubmission\" />
    <Folder Include="Features\AssignmentSubmission\Commands\UpdateAssignmentSubmission\" />
    <Folder Include="Features\AssignmentSubmission\Queries\" />
    <Folder Include="Features\OrganizationPositions\Commands\UpdateOrganizationPosition\" />
    <Folder Include="Features\Students\Queries\GetStudentsByCourse\" />
    <Folder Include="Features\Students\Queries\GetStudentDetail\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="13.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShepidiSoft.Domain\ShepidiSoft.Domain.csproj" />
  </ItemGroup>

</Project>
